[package]
name = "tribufu"
version = "0.0.3"
description = "TribuFu SDK"
repository = "https://github.com/TribuFu/SDK-RS"
authors = ["TribuFu <contact@tribufu.com>"]
license = "Apache-2.0"
readme = "README.md"
edition = "2021"
publish = true

exclude = [
    ".github/",
    ".vscode/",
    ".editorconfig",
    ".gitattributes",
]

[lib]
name = "TribuFu"
crate-type = ["rlib"]
path = "Source/lib.rs"

[dependencies]
