[package]
name = "tribufu"
version = "0.0.4"
description = "Tribufu SDK"
repository = "https://github.com/Tribufu/SDK-Rust"
authors = ["Tribufu <contact@tribufu.com>"]
license = "Apache-2.0"
readme = "README.md"
edition = "2021"
publish = true

exclude = [".github/", ".vscode/", ".editorconfig", ".gitattributes"]

[lib]
name = "tribufu"
crate-type = ["rlib"]
path = "src/lib.rs"

[dependencies]
alnilam-consts = { version = "0.0.4" }
anyhow = "1.0.75"
derive_more = "0.99.17"
reqwest = { version = "0.11.18", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
