[package]
name = "tribufu"
version = "0.0.2"
description = "TribuFu SDK"
repository = "https://github.com/TribuFu/SDK"
authors = ["TribuFu <contact@tribufu.com>"]
license = "Apache-2.0"
readme = "README.md"
edition = "2018"
publish = true

exclude = [
    ".github/",
    ".vscode/",
    "Documentation/",
    ".editorconfig",
    ".gitattributes",
    "*.code-workspace",
    "Bootstrap.ps1",
    "Bootstrap.sh",
]

[lib]
name="TribuFu"
crate-type = ["rlib"]
path = "Source/TribuFu.rs"

[dependencies]
